### ISSUE TITLE
Template needs to be updated to use nodejs12.x

### ISSUE THREAD

**Issue by srnly** [fortinet/fortigate-autoscale#19]
This template is failing to deploy due to nodejs8.10 being EOL.  We tried updating the runtime references to nodejs12.x but the deployment still fails when creating resources.  One of the errors was "Cannot find module 'uuid/v5'".  It looks like some modules are missing from the zip files.

**Comment by JaydenLiang** [comment]
@srnly thanks. We has finished the investigation of the issues. A new release for a quick fix will be published very soon.

**Comment by JaydenLiang** [comment]
Hi @srnly, we have released version 2.0.2 just now which resolved this issue.
