### ISSUE TITLE
Not authorized  image error

### ISSUE THREAD

**Issue by jisulove** [fortinet/fortigate-autoscale#2]
i've run cf template for aws autoscaling in ap-northeast-2 region.

but i've meet error "Not authorized image error ami-0a560b6c089c6310a"

How do i resolve this error?

**Comment by JaydenLiang** [comment]
> i've run cf template for aws autoscaling in ap-northeast-2 region.
> 
> but i've meet error "Not authorized image error ami-0a560b6c089c6310a"
> 
> How do i resolve this error?

It was due to the FortiGate AMI update on AWS marketplace but the template was not up to date.
The new release 1.0.3 has solved this problem.
